version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: mind-force
    ports:
      - 5432:5432

  rabbitmq:
    hostname: 'rabbitmq'
    image: rabbitmq:3.11.4-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_PLUGINS_DIR: /opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    # command: >
    #   bash -c "rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange &&
    #            rabbitmq-server"

    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      # - ./rabbitmq/log/:/var/log/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - ./rabbitmq/plugins:/usr/lib/rabbitmq/plugins
volumes:
  rabbitmq_logs:
